### PR TITLE
Network parameter removed to match model change.

### PR DESCRIPTION
**Pull request by reshmagiliyal**
Removed network parameter

### CODE REVIEW

**Comment by jainvipin** [comment]
thanks @reshmagiliyal for the PR; did sanity run pass?

**Comment by reshmagiliyal** [comment]
Hi Vipin,
      I ran make test-unit. And it passed successfully.

Thanks& Regards,
Reshma Giliyal

**Comment by jainvipin** [comment]
thanks @reshmagiliyal - will merge.

**Comment by jainvipin** [comment]
@reshmagiliyal - I wanted to test out your changes... seems like something is still amiss:
Following the instructions as in the README.md file, I get the following error with latest `netplugin` and `libcompose` code

```
ERRO[0000] Unable to create allow rule &client.Rule{Key:"", Action:"allow", Direction:"in", 
FromEndpointGroup:"example-web", FromIpAddress:"", FromNetwork:"dev",
PolicyName:"example-redis-in", Port:5001, Priority:2, Protocol:"tcp", RuleID:"2",
TenantName:"default", ToEndpointGroup:"", ToIpAddress:"", ToNetwork:"", LinkSets:client.RuleLinkSets{Policies:map[string]client.Link(nil)}}.
Error: Can not specify both from network and from EndpointGroup
```

**Pull request merged**
